### ISSUE TITLE
TypeError: t.map is not a function

### ISSUE THREAD

**Issue by dannystaple** [decaporg/decap-cms#6740]
**Describe the bug**

Traceback seen:
```
TypeError: t.map is not a function at https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:668:2698 at Ko (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:188:57930) at gs (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:188:104169) at ul (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:188:96717) at sl (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:188:96642) at Js (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:188:93672) at https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:188:45314 at t.unstable_runWithPriority (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:196:3844) at qi (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:188:45023) at Vi (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:188:45259)
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.192`
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36`

**CMS configuration**
```
backend:
  name: github
  repo: orionrobots/orionrobots.github.io
  branch: master
  base_url: https://github-oauth2.orionrobots.co.uk
media_folder: galleries
collections:
  - name: blog
    label: Blog
    folder: _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: post
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: string
        required: false
      - label: Tags
        name: tags
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: string
      - label: Category
        name: category
        widget: string
        required: false
      - label: Thumbnail
        name: thumb
        required: false
        widget: image
        allow_multiple: false
      - label: Lead image
        name: lead_image
        required: false
        widget: image
        allow_multiple: false
      - label: Body
        name: body
        widget: markdown
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
        id: date__\d{4}
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
      - description
    view_filters: []
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
public_folder: /galleries
isFetching: false
error: null

```

**Additional context**

It's likely that this is due to opening an old markdown/jekyll file authored pre-using netlify.

**Comment by martinjagodic** [comment]
Hi @dannystaple, please fill out all the fields in the issue template. The information you provided is not enough to debug the problem.

I'm closing the issue for now. Once you add the missing information, I can open it again.
